[package]
name = "content"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_http = { path = "../rust_http" }
tokio = { version = "1.46.0", features = ["full"] }
regex = "1.11.1"
dotenvy = "0.15.7"
deno_core = "0.352.0" # { version = "0.352.0", features = ["full"] }
serde_json = "1.0.140"
mlua = { version = "0.10.5", features = ["lua54", "vendored"] }

